services:
  postgres:
    image: postgres:15
    container_name: coderjam-postgres
    environment:
      POSTGRES_DB: coderjam
      POSTGRES_USER: coderjam
      POSTGRES_PASSWORD: coderjam123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U coderjam -d coderjam"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: